In [139]:
import pandas as pd 
import numpy as np

In [140]:
df=pd.read_csv("Leads.csv")
df.head().T

,0,1,2,3,4
Prospect ID,7927b2df-8bba-4d29-b9a2-b6e0beafe620,2a272436-5132-4136-86fa-dcc88c88f482,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,3256f628-e534-4826-9d63-4a8b88782852
Lead Number,660737,660728,660727,660719,660681
Lead Origin,API,API,Landing Page Submission,Landing Page Submission,Landing Page Submission
Lead Source,Olark Chat,Organic Search,Direct Traffic,Direct Traffic,Google
Do Not Email,No,No,No,No,No
Do Not Call,No,No,No,No,No
Converted,0,0,1,0,1
TotalVisits,0.0,5.0,2.0,1.0,2.0
Total Time Spent on Website,0,674,1532,305,1428
Page Views Per Visit,0.0,2.5,2.0,1.0,1.0
Last Activity,Page Visited on Website,Email Opened,Email Opened,Unreachable,Converted to Lead
Country,NaN,India,India,India,India
Specialization,Select,Select,Business Administration,Media and Advertising,Select
How did you hear about X Education,Select,Select,Select,Word Of Mouth,Other
What is your current occupation,Unemployed,Unemployed,Student,Unemployed,Unemployed
What matters most to you in choosing a course,Better Career Prospects,Better Career Prospects,Better Career Prospects,Better Career Prospects,Better Career Prospects
Search,No,No,No,No,No
Magazine,No,No,No,No,No
Newspaper Article,No,No,No,No,No
X Education Forums,No,No,No,No,No
Newspaper,No,No,No,No,No
Digital Advertisement,No,No,No,No,No
Through Recommendations,No,No,No,No,No
Receive More Updates About Our Courses,No,No,No,No,No
Tags,Interested in other courses,Ringing,Will revert after reading the email,Ringing,Will revert after reading the email
Lead Quality,Low in Relevance,NaN,Might be,Not Sure,Might be
Update me on Supply Chain Content,No,No,No,No,No
Get updates on DM Content,No,No,No,No,No
Lead Profile,Select,Select,Potential Lead,Select,Select
City,Select,Select,Mumbai,Mumbai,Mumbai
Asymmetrique Activity Index,02.Medium,02.Medium,02.Medium,02.Medium,02.Medium
Asymmetrique Profile Index,02.Medium,02.Medium,01.High,01.High,01.High
Asymmetrique Activity Score,15.0,15.0,14.0,13.0,15.0
Asymmetrique Profile Score,15.0,15.0,20.0,17.0,18.0
I agree to pay the amount through cheque,No,No,No,No,No
A free copy of Mastering The Interview,No,No,Yes,No,No
Last Notable Activity,Modified,Email Opened,Email Opened,Modified,Modified

In [141]:
df.dtypes

Prospect ID                                       object
Lead Number                                        int64
Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
How did you hear about X Education                object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                                          object
Newspaper Article                                 object
X Education Forums                                object
Newspaper                                         object
Digital Advertisement                             object
Through Recommendations                           object
Receive More Updates About Our Courses            object
Tags                                              object
Lead Quality                                      object
Update me on Supply Chain Content                 object
Get updates on DM Content                         object
Lead Profile                                      object
City                                              object
Asymmetrique Activity Index                       object
Asymmetrique Profile Index                        object
Asymmetrique Activity Score                      float64
Asymmetrique Profile Score                       float64
I agree to pay the amount through cheque          object
A free copy of Mastering The Interview            object
Last Notable Activity                             object
dtype: object

In [142]:
categorical=['lead_origin', 'lead_source', 'do_not_email',
       'do_not_call', 'last_activity', 'country', 'specialization',
       'how_did_you_hear_about_x_education', 'what_is_your_current_occupation',
       'what_matters_most_to_you_in_choosing_a_course', 'search', 'magazine',
       'newspaper_article', 'x_education_forums', 'newspaper',
       'digital_advertisement', 'through_recommendations',
       'receive_more_updates_about_our_courses', 'tags', 'lead_quality',
       'update_me_on_supply_chain_content', 'get_updates_on_dm_content',
       'lead_profile', 'city', 'asymmetrique_activity_index',
       'asymmetrique_profile_index',
       'i_agree_to_pay_the_amount_through_cheque',
       'a_free_copy_of_mastering_the_interview', 'last_notable_activity']#supprime col1
categorical=list(categorical)
numerical=['lead_number', 'totalvisits',
       'total_time_spent_on_website', 'page_views_per_visit',
       'asymmetrique_activity_score', 'asymmetrique_profile_score']
numerical=list(numerical)

In [143]:
#cleanin data set 
df.columns=df.columns.str.lower().str.replace(' ','_')
for c in categorical:
    df[c]=df[c].str.lower().str.replace(' ','_')

In [144]:
df.dtypes[df.isnull().sum()>0]

lead_source                                       object
totalvisits                                      float64
page_views_per_visit                             float64
last_activity                                     object
country                                           object
specialization                                    object
how_did_you_hear_about_x_education                object
what_is_your_current_occupation                   object
what_matters_most_to_you_in_choosing_a_course     object
tags                                              object
lead_quality                                      object
lead_profile                                      object
city                                              object
asymmetrique_activity_index                       object
asymmetrique_profile_index                        object
asymmetrique_activity_score                      float64
asymmetrique_profile_score                       float64
dtype: object

In [145]:
df.converted

0       0
1       0
2       1
3       0
4       1
       ..
9235    1
9236    0
9237    0
9238    1
9239    1
Name: converted, Length: 9240, dtype: int64

In [146]:
list(df.dtypes[df.isnull().sum()>0].index)

['lead_source',
 'totalvisits',
 'page_views_per_visit',
 'last_activity',
 'country',
 'specialization',
 'how_did_you_hear_about_x_education',
 'what_is_your_current_occupation',
 'what_matters_most_to_you_in_choosing_a_course',
 'tags',
 'lead_quality',
 'lead_profile',
 'city',
 'asymmetrique_activity_index',
 'asymmetrique_profile_index',
 'asymmetrique_activity_score',
 'asymmetrique_profile_score']

In [147]:
numerical=df.dtypes[(df.dtypes=='float64') |(df.dtypes=='int64')].index

In [148]:
#missing values
for c in categorical:
    df[c]=df[c].fillna('missing')
for v in numerical:
    df[v]=df[v].fillna(0)

In [149]:
df.dtypes[df.isnull().sum()>0]#check

Series([], dtype: object)

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...

>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
File:      c:\users\lenovo\anaconda3\lib\site-packages\sklearn\model_selection\_split.py
Type:      function

In [152]:
df_full,df_test=train_test_split(df,test_size=0.2,random_state=1)
df_train,df_val=train_test_split(df_full,test_size=0.25,random_state=1)
len(df),len(df_train)+len(df_test)+len(df_val)

(9240, 9240)

In [153]:
y_train=df_train.converted.values
y_test=df_test.converted.values
y_val=df_val.converted.values

del df_train['converted']
del df_test['converted']
del df_val['converted']

In [154]:
df_full.converted.value_counts()

converted
0    4560
1    2832
Name: count, dtype: int64

In [155]:
converted_rate=df_full.converted.mean()
converted_rate

np.float64(0.38311688311688313)

risk&diff

In [156]:
#diff
df_full.do_not_email.value_counts()

do_not_email
no     6801
yes     591
Name: count, dtype: int64

In [157]:
do_not_email_no=df_full[df.do_not_email=='no'].converted.mean()
do_not_email_yes=df_full[df.do_not_email=='yes'].converted.mean()
do_not_email_no,do_not_email_yes

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25596\1182624411.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  do_not_email_no=df_full[df.do_not_email=='no'].converted.mean()
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25596\1182624411.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  do_not_email_yes=df_full[df.do_not_email=='yes'].converted.mean()

(np.float64(0.4012645199235407), np.float64(0.17428087986463622))

In [158]:
do_not_email_yes-converted_rate,do_not_email_no-converted_rate

(np.float64(-0.2088360032522469), np.float64(0.01814763680665754))

In [159]:
from IPython.display import display

In [160]:

for c in categorical:
    df_group=df_full.groupby(c).converted.agg(['mean','count'])
    df_group['diff']=df_group['mean']-converted_rate
    df_group['risk']=df_group['mean']/converted_rate
    df_group=df_group.sort_values('diff',ascending=False)
    df_group=df_group.sort_values('risk',ascending=False)
    display(df_group)

                             mean  count      diff      risk
lead_origin
quick_add_form           1.000000      1  0.616883  2.610169
lead_add_form            0.919861    574  0.536744  2.400992
landing_page_submission  0.360677   3901 -0.022440  0.941427
api                      0.308414   2876 -0.074702  0.805014
lead_import              0.225000     40 -0.158117  0.587288

                       mean  count      diff      risk
lead_source
live_chat          1.000000      2  0.616883  2.610169
nc_edm             1.000000      1  0.616883  2.610169
welearn            1.000000      1  0.616883  2.610169
welingak_website   0.982906    117  0.599789  2.565551
reference          0.910588    425  0.527471  2.376790
missing            0.807692     26  0.424575  2.108214
click2call         0.750000      4  0.366883  1.957627
social_media       0.500000      2  0.116883  1.305085
google             0.400000   2295  0.016883  1.044068
organic_search     0.374320    919 -0.008797  0.977038
direct_traffic     0.317624   2037 -0.065493  0.829052
referral_sites     0.268041     97 -0.115076  0.699633
olark_chat         0.251768   1414 -0.131349  0.657157
facebook           0.225000     40 -0.158117  0.587288
bing               0.166667      6 -0.216450  0.435028
press_release      0.000000      2 -0.383117  0.000000
pay_per_click_ads  0.000000      1 -0.383117  0.000000
welearnblog_home   0.000000      1 -0.383117  0.000000
blog               0.000000      1 -0.383117  0.000000
youtubechannel     0.000000      1 -0.383117  0.000000

                  mean  count      diff      risk
do_not_email
no            0.401265   6801  0.018148  1.047368
yes           0.174281    591 -0.208836  0.454903

                 mean  count      diff      risk
do_not_call
yes          1.000000      1  0.616883  2.610169
no           0.383033   7391 -0.000083  0.999782

                                  mean  count      diff      risk
last_activity
approached_upfront            1.000000      8  0.616883  2.610169
email_received                1.000000      2  0.616883  2.610169
resubscribed_to_emails        1.000000      1  0.616883  2.610169
email_marked_spam             1.000000      2  0.616883  2.610169
missing                       0.780488     82  0.397371  2.037205
had_a_phone_conversation      0.727273     22  0.344156  1.898305
sms_sent                      0.627611   2202  0.244494  1.638172
email_opened                  0.363137   2729 -0.019980  0.947848
unreachable                   0.313433     67 -0.069684  0.818113
unsubscribed                  0.265306     49 -0.117811  0.692494
form_submitted_on_website     0.255102     98 -0.128015  0.665860
email_link_clicked            0.239437    213 -0.143680  0.624970
page_visited_on_website       0.231518    514 -0.151599  0.604300
view_in_browser_link_clicked  0.166667      6 -0.216450  0.435028
converted_to_lead             0.126437    348 -0.256680  0.330021
email_bounced                 0.092308    260 -0.290809  0.240939
olark_chat_conversation       0.086185    789 -0.296932  0.224958

                          mean  count      diff      risk
country
denmark               1.000000      1  0.616883  2.610169
oman                  0.750000      4  0.366883  1.957627
bahrain               0.666667      6  0.283550  1.740113
france                0.600000      5  0.216883  1.566102
asia/pacific_region   0.500000      2  0.116883  1.305085
bangladesh            0.500000      2  0.116883  1.305085
south_africa          0.500000      2  0.116883  1.305085
hong_kong             0.500000      4  0.116883  1.305085
missing               0.433283   1971  0.050166  1.130941
singapore             0.416667     12  0.033550  1.087571
united_kingdom        0.384615     13  0.001499  1.003911
india                 0.367986   5204 -0.015131  0.960506
united_arab_emirates  0.341463     41 -0.041653  0.891277
unknown               0.333333      3 -0.049784  0.870056
united_states         0.263158     57 -0.119959  0.686887
germany               0.250000      4 -0.133117  0.652542
australia             0.222222      9 -0.160895  0.580038
saudi_arabia          0.222222     18 -0.160895  0.580038
canada                0.000000      4 -0.383117  0.000000
china                 0.000000      1 -0.383117  0.000000
indonesia             0.000000      1 -0.383117  0.000000
italy                 0.000000      1 -0.383117  0.000000
kenya                 0.000000      1 -0.383117  0.000000
kuwait                0.000000      4 -0.383117  0.000000
liberia               0.000000      1 -0.383117  0.000000
netherlands           0.000000      1 -0.383117  0.000000
nigeria               0.000000      2 -0.383117  0.000000
russia                0.000000      1 -0.383117  0.000000
philippines           0.000000      2 -0.383117  0.000000
ghana                 0.000000      2 -0.383117  0.000000
qatar                 0.000000      5 -0.383117  0.000000
belgium               0.000000      2 -0.383117  0.000000
sri_lanka             0.000000      1 -0.383117  0.000000
sweden                0.000000      1 -0.383117  0.000000
switzerland           0.000000      1 -0.383117  0.000000
uganda                0.000000      2 -0.383117  0.000000
vietnam               0.000000      1 -0.383117  0.000000

                                       mean  count      diff      risk
specialization
healthcare_management              0.504065    123  0.120948  1.315695
marketing_management               0.479699    665  0.096582  1.252096
operations_management              0.470588    391  0.087471  1.228315
banking,_investment_and_insurance  0.458333    264  0.075216  1.196328
business_administration            0.457478    341  0.074361  1.194095
human_resource_management          0.455474    685  0.072358  1.188866
finance_management                 0.453865    802  0.070748  1.184665
supply_chain_management            0.423488    281  0.040371  1.105374
select                             0.418006   1555  0.034890  1.091068
media_and_advertising              0.411043    163  0.027926  1.072892
e-business                         0.408163     49  0.025046  1.065375
rural_and_agribusiness             0.400000     55  0.016883  1.044068
it_projects_management             0.375427    293 -0.007690  0.979927
hospitality_management             0.363636     88 -0.019481  0.949153
international_business             0.361702    141 -0.021415  0.944104
retail_management                  0.357143     84 -0.025974  0.932203
e-commerce                         0.356322     87 -0.026795  0.930060
travel_and_tourism                 0.350000    160 -0.033117  0.913559
services_excellence                0.310345     29 -0.072772  0.810053
missing                            0.102993   1136 -0.280124  0.268829

                                        mean  count      diff      risk
how_did_you_hear_about_x_education
student_of_someschool               0.475410    244  0.092293  1.240900
select                              0.474021   4061  0.090904  1.237276
advertisements                      0.450980     51  0.067864  1.177135
word_of_mouth                       0.441281    281  0.058164  1.151819
social_media                        0.428571     56  0.045455  1.118644
online_search                       0.425868    634  0.042751  1.111586
email                               0.421053     19  0.037936  1.099019
other                               0.412903    155  0.029786  1.077747
multiple_sources                    0.349593    123 -0.033523  0.912498
sms                                 0.200000     20 -0.183117  0.522034
missing                             0.132151   1748 -0.250966  0.344937

                                     mean  count      diff      risk
what_is_your_current_occupation
housewife                        1.000000      8  0.616883  2.610169
working_professional             0.916071    560  0.532955  2.391102
other                            0.615385     13  0.232268  1.606258
businessman                      0.500000      6  0.116883  1.305085
unemployed                       0.429491   4503  0.046375  1.121045
student                          0.359281    167 -0.023835  0.937785
missing                          0.143326   2135 -0.239791  0.374104

,mean,count,diff,risk
what_matters_most_to_you_in_choosing_a_course,,,,
flexibility_&_convenience,0.500000,2,0.116883,1.305085
better_career_prospects,0.482146,5237,0.099029,1.258483
missing,0.142127,2153,-0.240990,0.370976

            mean  count      diff      risk
search
no      0.383146   7381  0.000029  1.000076
yes     0.363636     11 -0.019481  0.949153

              mean  count  diff  risk
magazine
no        0.383117   7392   0.0   1.0

                       mean  count      diff      risk
newspaper_article
yes                1.000000      1  0.616883  2.610169
no                 0.383033   7391 -0.000083  0.999782

                        mean  count  diff  risk
x_education_forums
no                  0.383117   7392   0.0   1.0

               mean  count      diff      risk
newspaper
no         0.383169   7391  0.000052  1.000135
yes        0.000000      1 -0.383117  0.000000

                           mean  count      diff      risk
digital_advertisement
no                     0.383221   7390  0.000104  1.000271
yes                    0.000000      2 -0.383117  0.000000

                             mean  count      diff      risk
through_recommendations
yes                      0.750000      4  0.366883  1.957627
no                       0.382918   7388 -0.000199  0.999482

                                            mean  count  diff  risk
receive_more_updates_about_our_courses
no                                      0.383117   7392   0.0   1.0

,mean,count,diff,risk
tags,,,,
interested_in_next_batch,1.000000,4,0.616883,2.610169
lateral_student,1.000000,3,0.616883,2.610169
closed_by_horizzon,0.996454,282,0.613337,2.600914
lost_to_eins,0.979310,145,0.596193,2.556166
will_revert_after_reading_the_email,0.967013,1637,0.583896,2.524067
busy,0.567742,155,0.184625,1.481903
shall_take_in_the_next_coming_month,0.500000,2,0.116883,1.305085
in_touch_with_eins,0.272727,11,-0.110390,0.711864
missing,0.251030,2669,-0.132087,0.655232
in_confusion_whether_part_time_or_dlp,0.250000,4,-0.133117,0.652542
want_to_take_admission_but_has_financial_problems,0.250000,4,-0.133117,0.652542
opp_hangup,0.068966,29,-0.314151,0.180012
graduation_in_progress,0.063830,94,-0.319287,0.166607
ringing,0.028332,953,-0.354785,0.073950
interested_in_other_courses,0.023810,420,-0.359307,0.062147
diploma_holder_(not_eligible),0.020833,48,-0.362284,0.054379
switched_off,0.020408,196,-0.362709,0.053269
invalid_number,0.014493,69,-0.368624,0.037829
interested__in_full_time_mba,0.010989,91,-0.372128,0.028683
already_a_student,0.007752,387,-0.375365,0.020234
university_not_recognized,0.000000,2,-0.383117,0.000000
lost_to_others,0.000000,7,-0.383117,0.000000
still_thinking,0.000000,4,-0.383117,0.000000
recognition_issue_(dec_approval),0.000000,1,-0.383117,0.000000
number_not_provided,0.000000,22,-0.383117,0.000000
not_doing_further_education,0.000000,118,-0.383117,0.000000
wrong_number_given,0.000000,35,-0.383117,0.000000

                       mean  count      diff      risk
lead_quality
high_in_relevance  0.948718    507  0.565601  2.476315
low_in_relevance   0.803063    457  0.419947  2.096132
might_be           0.753392   1253  0.370275  1.966480
not_sure           0.242597    878 -0.140520  0.633219
missing            0.214605   3807 -0.168512  0.560155
worst              0.020408    490 -0.362709  0.053269

                                       mean  count  diff  risk
update_me_on_supply_chain_content
no                                 0.383117   7392   0.0   1.0

                               mean  count  diff  risk
get_updates_on_dm_content
no                         0.383117   7392   0.0   1.0

                                 mean  count      diff      risk
lead_profile
dual_specialization_student  1.000000     17  0.616883  2.610169
lateral_student              0.952381     21  0.569264  2.485876
potential_lead               0.781591   1282  0.398474  2.040086
select                       0.404403   3316  0.021286  1.055560
other_leads                  0.351621    401 -0.031496  0.917790
missing                      0.142127   2153 -0.240990  0.370976
student_of_someschool        0.024752    202 -0.358364  0.064608

                                 mean  count      diff      risk
city
select                       0.485479   1825  0.102363  1.267184
thane_&_outskirts            0.447412    599  0.064295  1.167822
other_cities_of_maharashtra  0.437326    359  0.054209  1.141495
other_cities                 0.408015    549  0.024898  1.064987
other_metro_cities           0.401961    306  0.018844  1.049186
mumbai                       0.401318   2579  0.018201  1.047509
tier_ii_cities               0.339286     56 -0.043831  0.885593
missing                      0.107239   1119 -0.275878  0.279911

                                 mean  count      diff      risk
asymmetrique_activity_index
02.medium                    0.428008   3042  0.044891  1.117173
missing                      0.382519   3375 -0.000598  0.998438
01.high                      0.313522    673 -0.069595  0.818344
03.low                       0.092715    302 -0.290402  0.242002

                                mean  count      diff      risk
asymmetrique_profile_index
01.high                     0.482525   1774  0.099408  1.259473
03.low                      0.416667     24  0.033550  1.087571
missing                     0.382519   3375 -0.000598  0.998438
02.medium                   0.304191   2219 -0.078926  0.793990

                                              mean  count  diff  risk
i_agree_to_pay_the_amount_through_cheque
no                                        0.383117   7392   0.0   1.0

                                           mean  count      diff      risk
a_free_copy_of_mastering_the_interview
no                                      0.39578   5071  0.012663  1.033053
yes                                     0.35545   2321 -0.027667  0.927785

                                  mean  count      diff      risk
last_notable_activity
approached_upfront            1.000000      1  0.616883  2.610169
email_marked_spam             1.000000      2  0.616883  2.610169
email_received                1.000000      1  0.616883  2.610169
resubscribed_to_emails        1.000000      1  0.616883  2.610169
had_a_phone_conversation      0.900000     10  0.516883  2.349153
sms_sent                      0.690286   1750  0.307169  1.801763
unreachable                   0.636364     22  0.253247  1.661017
email_opened                  0.364362   2256 -0.018755  0.951046
unsubscribed                  0.300000     40 -0.083117  0.783051
page_visited_on_website       0.294355    248 -0.088762  0.768316
modified                      0.230430   2721 -0.152687  0.601461
email_link_clicked            0.222222    135 -0.160895  0.580038
email_bounced                 0.160000     50 -0.223117  0.417627
olark_chat_conversation       0.156863    153 -0.226254  0.409438
form_submitted_on_website     0.000000      1 -0.383117  0.000000
view_in_browser_link_clicked  0.000000      1 -0.383117  0.000000

In [161]:
from sklearn.metrics import mutual_info_score

In [162]:
def mutual_info_churn_score(series):
    return mutual_info_score(series,df_full.converted)

In [163]:
m=df_full[categorical].apply(mutual_info_churn_score)
m.sort_values(ascending=False)

tags                                             0.376991
lead_quality                                     0.186122
lead_profile                                     0.113887
what_is_your_current_occupation                  0.092381
last_activity                                    0.088539
last_notable_activity                            0.072517
lead_source                                      0.062451
what_matters_most_to_you_in_choosing_a_course    0.055691
lead_origin                                      0.055599
how_did_you_hear_about_x_education               0.047740
specialization                                   0.037845
city                                             0.036014
asymmetrique_activity_index                      0.011616
asymmetrique_profile_index                       0.008983
do_not_email                                     0.008911
country                                          0.004992
a_free_copy_of_mastering_the_interview           0.000745
through_recommendations                          0.000151
digital_advertisement                            0.000131
do_not_call                                      0.000130
newspaper_article                                0.000130
newspaper                                        0.000065
search                                           0.000001
update_me_on_supply_chain_content                0.000000
get_updates_on_dm_content                        0.000000
receive_more_updates_about_our_courses           0.000000
x_education_forums                               0.000000
i_agree_to_pay_the_amount_through_cheque         0.000000
magazine                                         0.000000
dtype: float64

correlation

In [164]:
df_full[numerical].corrwith(df_full.converted)

lead_number                    0.021904
converted                      1.000000
totalvisits                    0.026085
total_time_spent_on_website    0.363470
page_views_per_visit          -0.009781
asymmetrique_activity_score    0.018662
asymmetrique_profile_score     0.027745
dtype: float64

In [165]:
from sklearn.feature_extraction import DictVectorizer

In [166]:
from  sklearn.linear_model import LogisticRegression

In [167]:
cols=['lead_origin', 'lead_source',
       'do_not_email', 'do_not_call', 'totalvisits',
       'total_time_spent_on_website', 'page_views_per_visit', 'last_activity',
       'country', 'specialization', 'how_did_you_hear_about_x_education',
       'what_is_your_current_occupation',
       'what_matters_most_to_you_in_choosing_a_course', 'search', 'magazine',
       'newspaper_article', 'x_education_forums', 'newspaper',
       'digital_advertisement', 'through_recommendations',
       'receive_more_updates_about_our_courses', 'tags', 'lead_quality',
       'update_me_on_supply_chain_content', 'get_updates_on_dm_content',
       'lead_profile', 'city', 'asymmetrique_activity_index',
       'asymmetrique_profile_index', 'asymmetrique_activity_score',
       'asymmetrique_profile_score',
       'i_agree_to_pay_the_amount_through_cheque',
       'a_free_copy_of_mastering_the_interview', 'last_notable_activity']

In [168]:
#validation 
train_dicts=df_train[cols].to_dict(orient='records')
val_dicts = df_val[cols].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
x_train=dv.transform(train_dicts)
x_val=dv.transform(val_dicts)

model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred_val=model.predict_proba(x_val)
converted_val=(y_pred_val>0.5)[:,1].astype(int)
m=(converted_val==y_val).mean()
print(m)

#model finale
y_full_train=df_full.converted.values
full_train_dicts=df_full[cols].to_dict(orient='records')
test_dicts=df_test[cols].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
x_full_train=dv.fit_transform(full_train_dicts)
x_test=dv.transform(test_dicts)
model=LogisticRegression(max_iter=1000)
model.fit(x_full_train,y_full_train)
y_pred_test=model.predict_proba(x_test)

converted_test=(y_pred_test>0.5)[:,1].astype(int)
m2=(converted_test==y_test).mean()
print(m2)

c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9393939393939394
0.9453463203463204

c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
len(df_full.lead_number.value_counts()),len(df_full)#le feature lead_number ne sert a rien c'est pourquoi jai supprimé du categories

(7392, 7392)

In [195]:
#customer
dicts_client=test_dicts[20]
y_client=y_test[20]

dv=DictVectorizer(sparse=False)
x_full_train=dv.fit_transform(full_train_dicts)
x_client=dv.transform(dicts_client)
model=LogisticRegression(max_iter=1000)
model.fit(x_full_train,y_full_train)
y_pred_client=model.predict_proba(x_client)

print(((y_pred_client>0.5)[:,1].astype(int)==y_client))
print((y_pred_client>0.5)[:,1].astype(int),y_client)

[ True]
[1] 1

c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [201]:
dicts_client=test_dicts[80]
y_client=y_test[80]
x_client=dv.transform(dicts_client)
y_pred_client=model.predict_proba(x_client)

print(((y_pred_client>0.5)[:,1].astype(int)==y_client))
print((y_pred_client>0.5)[:,1].astype(int),y_client)

[ True]
[1] 1